### ISSUE TITLE
AttributeError: module 'gswrap' has no attribute 'Client'

### ISSUE THREAD

**Issue by JulianOestreich90** [Parquery/gs-wrap#32]
Library is not usable, because you can't create a Client Object. I deinstalled all other python packages for gcloud and reinstalled but it still does not work. Thats quite sad, because your wrapper seems to be the only python library that supports parallelization for gcloud storage bulk copying.

**Comment by mristin** [comment]
Hi @JulianOestreich90 ,
Could you please send a snippet that doesn't work and the exact versions of the dependencies so that I can reproduce the error?

**Comment by JulianOestreich90** [comment]
I made a misstake here and used the wrong package because there is also a `gswrap` package. You can delete the issue.
